"""Phase 2A normalized signal input contracts."""

from .service import IngestionService
from .replay import (
    FixtureSignal,
    replay_fixture_signals,
)
from .models import (
    CIRunSignal,
    IssueSignal,
    LocalLogSignal,
    SignalEvent,
    SignalSource,
    normalize_ci_run,
    normalize_issue,
    normalize_local_log,
)
from .github_readonly import (
    FixtureTransport,
    GitHubAdapterError,
    GitHubCIRunSignal,
    GitHubIssueSignal,
    GitHubRateLimit,
    GitHubRateLimitKind,
    GitHubReadOnlyAdapter,
    GhApiTransport,
    ReadonlyGitHubTransport,
    parse_ci_runs,
    parse_issues,
    classify_github_rate_limit,
    classify_rate_limit,
)
from .github_ingestion import ingest_github_snapshot
from .ha_adapter import (
    HAAdapterError,
    HAContext,
    HAFact,
    HADecision,
    HAExecution,
    HAProgressEntry,
    HATaskContext,
    read_ha_context,
    read_fact_context,
    read_decision_context,
    read_task_context,
)
from .diagnostics import (
    DiagnosticError,
    HADiagnosticCounts,
    HADiagnosticDecision,
    HADiagnosticFact,
    HADiagnosticReport,
    HADiagnosticTask,
    build_diagnostic_summary,
    build_ledger_diagnostic_summary,
    read_diagnostic_summary,
)
__all__ = [
    "IngestionService",
    "FixtureSignal",
    "replay_fixture_signals",
    "CIRunSignal",
    "IssueSignal",
    "LocalLogSignal",
    "SignalEvent",
    "SignalSource",
    "normalize_ci_run",
    "normalize_issue",
    "normalize_local_log",
    "FixtureTransport",
    "GitHubAdapterError",
    "GitHubCIRunSignal",
    "GitHubIssueSignal",
    "GitHubRateLimit",
    "GitHubRateLimitKind",
    "GitHubReadOnlyAdapter",
    "GhApiTransport",
    "ReadonlyGitHubTransport",
    "parse_ci_runs",
    "parse_issues",
    "classify_github_rate_limit",
    "classify_rate_limit",
    "ingest_github_snapshot",
    "HAAdapterError",
    "HAContext",
    "HAFact",
    "HADecision",
    "HAExecution",
    "HAProgressEntry",
    "HATaskContext",
    "read_ha_context",
    "read_fact_context",
    "read_decision_context",
    "read_task_context",
    "DiagnosticError",
    "HADiagnosticCounts",
    "HADiagnosticDecision",
    "HADiagnosticFact",
    "HADiagnosticReport",
    "HADiagnosticTask",
    "build_diagnostic_summary",
    "build_ledger_diagnostic_summary",
    "read_diagnostic_summary",
]
